TOPDIR=../..
include $(TOPDIR)/dfmakefiles/defs.make

NOINSTALL=defined

INCLUDE_DIR=$(includedir)/linux/compat
INCLUDE_FILES=$(wildcard *.h *.imp)

DONT_INCLUDE_DEPS=defined
include $(TOPDIR)/dfmakefiles/rules.make

